language: python
cache: pip
python:
    - "2.6"
    - "2.7"
    - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
    - pip install -r requirements.txt
script:
    - nosetests --with-coverage --cover-package=remarkable
    - flake8 remarkable setup.py tests
after_success:
  - coveralls
