language: python
python:
    - "2.6"
    - "2.7"
    - "3.6"
install:
    - pip install -r requirements.txt
script:
    - nosetests --with-coverage --cover-package=remarkable
    - flake8 remarkable setup.py tests
after_success:
  - coveralls
